"""initial schema

Revision ID: 8df715d4afd9
Revises: 
Create Date: 2026-05-29 04:41:19.645673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df715d4afd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actividades_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('uq_actividades_nombre_active', ['nombre'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('role', sa.Enum('client', 'employee', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo', name='dia_semana'), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('cupo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turnos_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('uq_actividad_dia_hora_active', ['actividad_id', 'dia_semana', 'hora'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))

    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('eventual', 'mensual', name='reserva_tipo'), nullable=False),
    sa.Column('motivo_cancelacion', sa.Enum('reembolsado', 'cancelado', name='motivo_cancelacion'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservas_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('uq_reserva_user_turno_fecha_active', ['user_id', 'turno_id', 'fecha'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))

    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('pagado', 'senado', 'cancelado', 'reembolsado', name='pago_estado'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_deleted_at'))

    op.drop_table('pagos')
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_index('uq_reserva_user_turno_fecha_active', postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_reservas_deleted_at'))

    op.drop_table('reservas')
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.drop_index('uq_actividad_dia_hora_active', postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_turnos_deleted_at'))

    op.drop_table('turnos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_index('uq_actividades_nombre_active', postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_actividades_deleted_at'))

    op.drop_table('actividades')
    # ### end Alembic commands ###
