"""agrega tabla clases y actualiza reservas

Revision ID: 9f90ebb52ac9
Revises: 8df715d4afd9
Create Date: 2026-06-03 02:55:55.461680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f90ebb52ac9'
down_revision = '8df715d4afd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cupo_disponible', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turno_id', 'fecha', name='uq_clase_turno_fecha')
    )
    with op.batch_alter_table('clases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clases_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clase_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('uq_reserva_user_turno_fecha_active'), postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index('uq_reserva_user_clase_active', ['user_id', 'clase_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_constraint(batch_op.f('reservas_turno_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clases', ['clase_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('fecha')
        batch_op.drop_column('turno_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turno_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reservas_turno_id_fkey'), 'turnos', ['turno_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('uq_reserva_user_clase_active', postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index(batch_op.f('uq_reserva_user_turno_fecha_active'), ['user_id', 'turno_id', 'fecha'], unique=True, postgresql_where='(deleted_at IS NULL)')
        batch_op.drop_column('clase_id')

    with op.batch_alter_table('clases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clases_deleted_at'))

    op.drop_table('clases')
    # ### end Alembic commands ###
