"""Crear tablas con actividades

Revision ID: 930fe49b6367
Revises: 
Create Date: 2026-05-21 22:31:57.215321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930fe49b6367'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('costo_individual', sa.Float(), nullable=False),
    sa.Column('costo_mensual', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('actividad_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.DateTime(), nullable=False),
    sa.Column('cupo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.actividad_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_turno'], ['turnos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_turno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscripciones')
    op.drop_table('turnos')
    op.drop_table('usuarios')
    op.drop_table('actividades')
    # ### end Alembic commands ###
